# IMAP server and email fetcher.

version: '2'

services:
  dg6:
    image: ghcr.io/tctlrd/ddg6:latest
    volumes:
      - /srv/mail/home/:/home/
      - /srv/mail/ssl:/etc/ssl/private:ro
    evironment:
      - CRON="*/30 * * * *"
      - TZ=UTC
    ports:
      - "143:143"  # imap
      - "993:993"  # imaps
      - "4190:4190"  # managesieve
    restart: unless-stopped
